-- Autogenerated: do not edit this file

UPDATE MMS_GLOBAL_CONFIGURATION SET CODE = '6' WHERE NAME = 'GLOBAL_VERSION';


INSERT INTO MMS_SCHEDULE (DISPLAY_NAME, JOB_NAME, ACTION_TYPE, URL, DESCRIPTION, STATUS) VALUES ('自动发送休假上年结余和休假调整数失效提醒', 'AUTO_SEND_MAIL_FOR_LEA', 4, 'AUTO_SEND_MAIL_FOR_LEA', '请到休假政策设置其它设置中为需要提醒的假期种类设置到期提醒天数，此自动任务计划支持MMS 2.0-2016-09-30及以上的版本。','E');


